export const LABELS = {
  en: {
    appName: 'Invoice Studio',
    history: 'History',
    settings: 'Agency details',
    newInvoice: 'New invoice',
    print: 'Print / Save PDF',
    editorTitle: 'Invoice details',
    invoiceNumber: 'Invoice No.',
    date: 'Date',
    dueDate: 'Due Date',
    clientDetails: 'Client details',
    buyerName: 'Organization / buyer name',
    buyerVat: 'Buyer VAT number (optional)',
    buyerCr: 'CR Number',
    buyerAddress: 'Address',
    description: 'Description',
    qty: 'Qty',
    unitPrice: 'Unit price',
    lineTotal: 'Amount',
    addItem: '+ Add line item',
    billTo: 'Bill to',
    subtotal: 'Subtotal',
    vat: 'VAT (15%)',
    total: 'Total due',
    sar: 'SAR',
    vatNumber: 'VAT Number',
    crNumber: 'CR Number',
    phone: 'Phone',
    email: 'Email',
    notes: 'Notes',
    scanToVerify: 'Scan to verify',
    invoiceTitle: 'TAX INVOICE',
    itemDescPh: 'e.g. Logo design & branding',
    setupTitle: 'Agency Details',
    uploadLogo: 'Upload Logo',
    agencyNameAr: 'Agency Name (Arabic)',
    agencyNameEn: 'Agency Name (English)',
    cancel: 'Cancel',
    save: 'Save',
    historyTitle: 'Invoice History',
    close: 'Close',
    load: 'Load',
    confirmDeleteHistory: 'Delete this history item?'
  },
  ar: {
    appName: 'استوديو الفواتير',
    history: 'السجل',
    settings: 'تفاصيل المنشأة',
    newInvoice: 'فاتورة جديدة',
    print: 'طباعة / حفظ PDF',
    editorTitle: 'تفاصيل الفاتورة',
    invoiceNumber: 'رقم الفاتورة',
    date: 'التاريخ',
    dueDate: 'تاريخ الاستحقاق',
    clientDetails: 'بيانات العميل',
    buyerName: 'اسم العميل / الشركة',
    buyerVat: 'الرقم الضريبي للعميل (اختياري)',
    buyerCr: 'رقم السجل التجاري',
    buyerAddress: 'العنوان',
    description: 'الوصف',
    qty: 'الكمية',
    unitPrice: 'سعر الوحدة',
    lineTotal: 'المبلغ الإجمالي',
    addItem: '+ إضافة صنف',
    billTo: 'فاتورة إلى',
    subtotal: 'المجموع الفرعي',
    vat: 'ضريبة القيمة المضافة (15%)',
    total: 'الإجمالي المستحق',
    sar: 'ر.س',
    vatNumber: 'الرقم الضريبي',
    crNumber: 'السجل التجاري',
    phone: 'الهاتف',
    email: 'البريد',
    notes: 'ملاحظات',
    scanToVerify: 'مسح للتحقق',
    invoiceTitle: 'فاتورة ضريبية',
    itemDescPh: 'الوصف',
    setupTitle: 'بيانات المنشأة',
    uploadLogo: 'رفع شعار',
    agencyNameAr: 'اسم المنشأة (عربي)',
    agencyNameEn: 'اسم المنشأة (إنجليزي)',
    cancel: 'إلغاء',
    save: 'حفظ',
    historyTitle: 'سجل الفواتير',
    close: 'إغلاق',
    load: 'تحميل',
    confirmDeleteHistory: 'هل تريد حذف هذا العنصر؟'
  }
};