export const LABELS = {
  en: {
    dir: 'ltr',
    code: 'en',
    appName: 'Invoice Studio',
    langToggle: 'العربية',
    newInvoice: 'New invoice',
    print: 'Print / Save PDF',
    settings: 'Agency details',
    history: 'History',
    invoiceTitle: 'TAX INVOICE',
    invoiceNumber: 'Invoice No.',
    date: 'Date',
    billTo: 'Bill to',
    billedBy: 'Billed by',
    buyerName: 'Organization / buyer name',
    buyerNamePh: 'e.g. Al Salam Marketing Co.',
    buyerVat: 'Buyer VAT number (optional)',
    description: 'Description',
    qty: 'Qty',
    unitPrice: 'Unit price',
    lineTotal: 'Amount',
    addItem: 'Add line',
    remove: 'Remove',
    subtotal: 'Subtotal',
    vat: 'VAT (15%)',
    total: 'Total due',
    notes: 'Notes',
    notesPlaceholder: 'Payment terms, bank details, thank-you note...',
    sar: 'SAR',
    vatNumberLabel: 'VAT Registration No.',
    crNumberLabel: 'C.R. Number',
    scanToVerify: 'Scan to verify (ZATCA)',
    agencyName: 'Agency name (English)',
    agencyNameAr: 'Agency name (Arabic)',
    agencyAddress: 'Address (English)',
    agencyAddressAr: 'Address (Arabic)',
    phone: 'Phone',
    email: 'Email',
    logo: 'Logo',
    uploadLogo: 'Upload logo',
    removeLogo: 'Remove',
    save: 'Save details',
    close: 'Close',
    cancel: 'Cancel',
    noItems: 'Add your first line item to begin.',
    editorTitle: 'Invoice details',
    previewTitle: 'Preview',
    itemDescPh: 'e.g. Logo design & brand guidelines',
    setupTitle: 'Set up your agency',
    setupBody: "Enter your agency's details once — they'll appear on every invoice you create.",
    historyEmpty: 'Printed invoices will show up here.',
    load: 'Load',
    delete: 'Delete',
    confirmDeleteHistory: 'Delete this invoice from history?',
    savedToHistory: 'Saved to history',
    optional: 'optional',
    required: 'This field is required',
    invoiceForLabel: 'Invoice for',
  },
  ar: {
    dir: 'rtl',
    code: 'ar',
    appName: 'استوديو الفواتير',
    langToggle: 'English',
    newInvoice: 'فاتورة جديدة',
    print: 'طباعة / حفظ PDF',
    settings: 'بيانات المنشأة',
    history: 'السجل',
    invoiceTitle: 'فاتورة ضريبية',
    invoiceNumber: 'رقم الفاتورة',
    date: 'التاريخ',
    billTo: 'فاتورة إلى',
    billedBy: 'من',
    buyerName: 'اسم الجهة / العميل',
    buyerNamePh: 'مثال: شركة السلام للتسويق',
    buyerVat: 'الرقم الضريبي للعميل (اختياري)',
    description: 'الوصف',
    qty: 'الكمية',
    unitPrice: 'سعر الوحدة',
    lineTotal: 'الإجمالي',
    addItem: 'إضافة بند',
    remove: 'حذف',
    subtotal: 'المجموع الفرعي',
    vat: 'ضريبة القيمة المضافة (15%)',
    total: 'الإجمالي المستحق',
    notes: 'ملاحظات',
    notesPlaceholder: 'شروط الدفع، بيانات الحساب البنكي، رسالة شكر...',
    sar: 'ر.س',
    vatNumberLabel: 'الرقم الضريبي',
    crNumberLabel: 'رقم السجل التجاري',
    scanToVerify: 'امسح للتحقق (زاتكا)',
    agencyName: 'اسم المنشأة (إنجليزي)',
    agencyNameAr: 'اسم المنشأة (عربي)',
    agencyAddress: 'العنوان (إنجليزي)',
    agencyAddressAr: 'العنوان (عربي)',
    phone: 'الهاتف',
    email: 'البريد الإلكتروني',
    logo: 'الشعار',
    uploadLogo: 'رفع الشعار',
    removeLogo: 'إزالة',
    save: 'حفظ البيانات',
    close: 'إغلاق',
    cancel: 'إلغاء',
    noItems: 'أضف أول بند للبدء.',
    editorTitle: 'تفاصيل الفاتورة',
    previewTitle: 'معاينة',
    itemDescPh: 'مثال: تصميم شعار ودليل الهوية البصرية',
    setupTitle: 'إعداد بيانات المنشأة',
    setupBody: 'أدخل بيانات منشأتك مرة واحدة، وستظهر تلقائياً في كل فاتورة.',
    historyEmpty: 'ستظهر هنا الفواتير التي تمت طباعتها.',
    load: 'فتح',
    delete: 'حذف',
    confirmDeleteHistory: 'هل تريد حذف هذه الفاتورة من السجل؟',
    savedToHistory: 'تم الحفظ في السجل',
    optional: 'اختياري',
    required: 'هذا الحقل مطلوب',
    invoiceForLabel: 'فاتورة رقم',
  },
};
