export const LABELS = {
  en: {
    dir: 'ltr',
    code: 'en',
    appName: 'Invoice Studio',
    langToggle: 'العربية',
    newInvoice: 'New invoice',
    print: 'Print / Save PDF',
    settings: 'Agency details',
    history: 'History',
    invoiceTitle: 'TAX INVOICE',
    invoiceNumber: 'Invoice No.',
    date: 'Date',
    billTo: 'Bill to',
    billedBy: 'Billed by',
    buyerName: 'Organization / buyer name',
    buyerNamePh: 'e.g. Al Salam Marketing Co.',
    buyerVat: 'Buyer VAT number (optional)',
    description: 'Description',
    qty: 'Qty',
    unitPrice: 'Unit price',
    lineTotal: 'Amount',
    addItem: 'Add line',
    remove: 'Remove',
    subtotal: 'Subtotal',
    vat: 'VAT (15%)',
    total: 'Total due',
    notes: 'Notes',
    notesPlaceholder: 'Payment terms, bank details, thank-you note...',
    sar: 'SAR',
    vatNumberLabel: 'VAT Registration No.',
    crNumberLabel: 'C.R. Number',
    scanToVerify: 'Scan to verify (ZATCA)',
    agencyName: 'Agency name (English)',
    agencyNameAr: 'Agency name (Arabic)',
    agencyAddress: 'Address (English)',
    agencyAddressAr: 'Address (Arabic)',
    phone: 'Phone',
    email: 'Email',
    logo: 'Logo',
    uploadLogo: 'Upload logo',
    removeLogo: 'Remove',
    save: 'Save details',
    close: 'Close',
    cancel: 'Cancel',
    noItems: 'Add your first line item to begin.',
    editorTitle: 'Invoice details',
    previewTitle: 'Preview',
    itemDescPh: 'e.g. Logo design & brand guidelines',
    setupTitle: 'Set up your agency',
    setupBody: "Enter your agency's details once — they'll appear on every invoice you create.",
    historyEmpty: 'Printed invoices will show up here.',
    load: 'Load',
    delete: 'Delete',
    confirmDeleteHistory: 'Delete this invoice from history?',
    savedToHistory: 'Saved to history',
    optional: 'optional',
    required: 'This field is required',
    invoiceForLabel: 'Invoice for',
    buyerInfoSection: 'Buyer / Organization Information',
    buyerCrNumber: 'CR Number',
    buyerAddressLabel: 'Buyer Address',
    buyerPhoneLabel: 'Mobile / Phone',
    buyerEmailLabel: 'Email Address',
    paymentSection: 'Payment Terms & Split Payments',
    paymentOption: 'Payment Option',
    paidFull: 'Paid in Full',
    halfPayment: 'Half Payment (50%)',
    customPartial: 'Custom Partial Payment',
    dueDateForBalance: 'Due Date for Remaining Balance',
    amountPaidLabel: 'Amount Paid',
    remainingBalanceLabel: 'Remaining Balance',
    addLine: '+ Add line',
    savePdf: 'Save as PDF',
    dueDateInline: 'Due Date',
    paidAmountInline: 'Paid Amount',
    remainingBalanceInline: 'Remaining Balance',
    vatShort: 'VAT',
    crShort: 'CR',
    docTypeToggleLabel: 'Document Type',
    docTypeInvoice: 'Tax Invoice',
    docTypeQuotation: 'Quotation',
    quotationNumber: 'Quotation No.',
    quotationFor: 'Quotation For',
    quotationTitle: 'QUOTATION',
    estimatedTotal: 'Estimated Total',
    validUntil: 'Valid Until',
    convertToInvoice: 'Convert to Invoice',
    duplicateDoc: 'Duplicate',
    discountLabel: 'Discount',
    discountNone: 'No discount',
    discountPercent: 'Percentage (%)',
    discountFixed: 'Fixed amount',
    discountValueLabel: 'Discount Value',
    paymentInstallments: 'Yearly Payment Plan (Installments)',
    installmentCountLabel: 'Number of Installments',
    installmentFrequencyLabel: 'Frequency',
    frequencyMonthly: 'Monthly',
    frequencyQuarterly: 'Quarterly',
    installmentStartLabel: 'First Payment Date',
    installmentScheduleTitle: 'Payment Schedule',
    installmentNumberCol: '#',
    installmentDueCol: 'Due Date',
    installmentAmountCol: 'Amount',
    docBadgeInvoice: 'Invoice',
    docBadgeQuotation: 'Quotation',
    quotationValiditySection: 'Quotation Validity',

    // License activation & subscription status
    activateTitle: 'Activate Invoice Studio',
    activateBody: 'Enter the license key from your purchase confirmation email to get started.',
    licenseKeyLabel: 'License key',
    licenseKeyPh: 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX',
    activateButton: 'Activate',
    activating: 'Activating…',
    activateError: 'Could not activate that key. Double-check it and try again.',
    activateOffline: "Couldn't reach the license server. Check your internet connection and try again.",
    licenseExpiredBanner: 'Your subscription has expired. Renew to keep creating new invoices — you can still view, print, and export everything already saved.',
    licenseGraceBanner: "Couldn't verify your subscription (no internet for a while). Reconnect soon to keep creating new invoices.",
    licenseDisabledBanner: 'This license key has been disabled. Contact support or activate a different key.',
    renewNow: 'Renew subscription',
    enterDifferentKey: 'Enter a different key',
    lockedTooltip: 'Renew your subscription to create new documents',

    // Backup & export
    backupSection: 'Backups & Export',
    exportAllJson: 'Export all (JSON)',
    exportAllCsv: 'Export all (CSV)',
    exportSuccess: 'Saved',
    exportNothingToSave: 'No saved invoices yet to export.',
    autoBackupNote: 'Every invoice is also backed up automatically to a file on this computer.',
    autoBackupPath: 'Backup folder',
  },
  ar: {
    dir: 'rtl',
    code: 'ar',
    appName: 'استوديو الفواتير',
    langToggle: 'English',
    newInvoice: 'فاتورة جديدة',
    print: 'طباعة / حفظ PDF',
    settings: 'بيانات المنشأة',
    history: 'السجل',
    invoiceTitle: 'فاتورة ضريبية',
    invoiceNumber: 'رقم الفاتورة',
    date: 'التاريخ',
    billTo: 'فاتورة إلى',
    billedBy: 'من',
    buyerName: 'اسم الجهة / العميل',
    buyerNamePh: 'مثال: شركة السلام للتسويق',
    buyerVat: 'الرقم الضريبي للعميل (اختياري)',
    description: 'الوصف',
    qty: 'الكمية',
    unitPrice: 'سعر الوحدة',
    lineTotal: 'الإجمالي',
    addItem: 'إضافة بند',
    remove: 'حذف',
    subtotal: 'المجموع الفرعي',
    vat: 'ضريبة القيمة المضافة (15%)',
    total: 'الإجمالي المستحق',
    notes: 'ملاحظات',
    notesPlaceholder: 'شروط الدفع، بيانات الحساب البنكي، رسالة شكر...',
    sar: 'ر.س',
    vatNumberLabel: 'الرقم الضريبي',
    crNumberLabel: 'رقم السجل التجاري',
    scanToVerify: 'امسح للتحقق (زاتكا)',
    agencyName: 'اسم المنشأة (إنجليزي)',
    agencyNameAr: 'اسم المنشأة (عربي)',
    agencyAddress: 'العنوان (إنجليزي)',
    agencyAddressAr: 'العنوان (عربي)',
    phone: 'الهاتف',
    email: 'البريد الإلكتروني',
    logo: 'الشعار',
    uploadLogo: 'رفع الشعار',
    removeLogo: 'إزالة',
    save: 'حفظ البيانات',
    close: 'إغلاق',
    cancel: 'إلغاء',
    noItems: 'أضف أول بند للبدء.',
    editorTitle: 'تفاصيل الفاتورة',
    previewTitle: 'معاينة',
    itemDescPh: 'مثال: تصميم شعار ودليل الهوية البصرية',
    setupTitle: 'إعداد بيانات المنشأة',
    setupBody: 'أدخل بيانات منشأتك مرة واحدة، وستظهر تلقائياً في كل فاتورة.',
    historyEmpty: 'ستظهر هنا الفواتير التي تمت طباعتها.',
    load: 'فتح',
    delete: 'حذف',
    confirmDeleteHistory: 'هل تريد حذف هذه الفاتورة من السجل؟',
    savedToHistory: 'تم الحفظ في السجل',
    optional: 'اختياري',
    required: 'هذا الحقل مطلوب',
    invoiceForLabel: 'فاتورة رقم',
    buyerInfoSection: 'بيانات الجهة / العميل',
    buyerCrNumber: 'الرقم التجاري',
    buyerAddressLabel: 'عنوان العميل',
    buyerPhoneLabel: 'الجوال / الهاتف',
    buyerEmailLabel: 'البريد الإلكتروني',
    paymentSection: 'شروط الدفع والدفعات الجزئية',
    paymentOption: 'طريقة الدفع',
    paidFull: 'دفع كامل',
    halfPayment: 'دفعة نصف (50%)',
    customPartial: 'دفعة جزئية مخصّصة',
    dueDateForBalance: 'تاريخ استحقاق المبلغ المتبقي',
    amountPaidLabel: 'المبلغ المدفوع',
    remainingBalanceLabel: 'المبلغ المتبقي',
    addLine: '+ إضافة بند',
    savePdf: 'حفظ كملف PDF',
    dueDateInline: 'تاريخ الاستحقاق',
    paidAmountInline: 'المبلغ المدفوع',
    remainingBalanceInline: 'الرصيد المتبقي',
    vatShort: 'ضريبة',
    crShort: 'س.ت',
    docTypeToggleLabel: 'نوع المستند',
    docTypeInvoice: 'فاتورة ضريبية',
    docTypeQuotation: 'عرض سعر',
    quotationNumber: 'رقم عرض السعر',
    quotationFor: 'عرض السعر إلى',
    quotationTitle: 'عرض سعر',
    estimatedTotal: 'الإجمالي التقديري',
    validUntil: 'صالح حتى',
    convertToInvoice: 'تحويل إلى فاتورة',
    duplicateDoc: 'نسخ',
    discountLabel: 'الخصم',
    discountNone: 'بدون خصم',
    discountPercent: 'نسبة مئوية (%)',
    discountFixed: 'مبلغ ثابت',
    discountValueLabel: 'قيمة الخصم',
    paymentInstallments: 'خطة الدفع السنوية (تقسيط)',
    installmentCountLabel: 'عدد الدفعات',
    installmentFrequencyLabel: 'التكرار',
    frequencyMonthly: 'شهري',
    frequencyQuarterly: 'ربع سنوي',
    installmentStartLabel: 'تاريخ أول دفعة',
    installmentScheduleTitle: 'جدول الدفعات',
    installmentNumberCol: '#',
    installmentDueCol: 'تاريخ الاستحقاق',
    installmentAmountCol: 'المبلغ',
    docBadgeInvoice: 'فاتورة',
    docBadgeQuotation: 'عرض سعر',
    quotationValiditySection: 'صلاحية العرض',

    // License activation & subscription status
    activateTitle: 'تفعيل استوديو الفواتير',
    activateBody: 'أدخل رمز الترخيص من رسالة تأكيد الشراء للبدء.',
    licenseKeyLabel: 'رمز الترخيص',
    licenseKeyPh: 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX',
    activateButton: 'تفعيل',
    activating: 'جارٍ التفعيل…',
    activateError: 'تعذّر تفعيل هذا الرمز. تأكد منه وحاول مرة أخرى.',
    activateOffline: 'تعذّر الوصول إلى خادم التراخيص. تحقق من اتصالك بالإنترنت وحاول مرة أخرى.',
    licenseExpiredBanner: 'انتهى اشتراكك. جدّده لإنشاء فواتير جديدة — يمكنك الاستمرار في عرض وطباعة وتصدير كل ما تم حفظه مسبقاً.',
    licenseGraceBanner: 'تعذّر التحقق من اشتراكك (لا يوجد اتصال بالإنترنت منذ فترة). أعد الاتصال قريباً لمتابعة إنشاء فواتير جديدة.',
    licenseDisabledBanner: 'تم تعطيل رمز الترخيص هذا. تواصل مع الدعم أو فعّل رمزاً آخر.',
    renewNow: 'تجديد الاشتراك',
    enterDifferentKey: 'إدخال رمز آخر',
    lockedTooltip: 'جدّد اشتراكك لإنشاء مستندات جديدة',

    // Backup & export
    backupSection: 'النسخ الاحتياطي والتصدير',
    exportAllJson: 'تصدير الكل (JSON)',
    exportAllCsv: 'تصدير الكل (CSV)',
    exportSuccess: 'تم الحفظ',
    exportNothingToSave: 'لا توجد فواتير محفوظة للتصدير بعد.',
    autoBackupNote: 'يتم أيضاً حفظ نسخة احتياطية من كل فاتورة تلقائياً في ملف على هذا الجهاز.',
    autoBackupPath: 'مجلد النسخ الاحتياطي',
  },
};